export const projectRoles = [
  "Front-end Developer",
  "Back-end Developer",
  "Product Manager",
  "Project Manager",
  "Quality Assurance Engineer",
  "UX Designer",
  "UI Designer",
  "DevOps Engineer",
  "System Architect",
  "Database Administrator",
  "Business Analyst",
  "Data Analyst",
  "Marketing Manager",
  "Content Manager",
  "Social Media Manager",
  "SEO Specialist",
  "HR Manager",
  "Sales Manager",
  "Customer Support Specialist",
  "Brand Manager",
  "Market Research Analyst",
] as const;

export const projectDomains = [
  "Work & Productivity",
  "Engineering & Development",
  "Design & Creative",
  "Finance",
  "Social & Community",
  "Marketing & Sales",
  "AI",
  "Health & Fitness",
  "Travel",
  "Platforms",
  "Product add-ons",
  "Web3",
  "Physical Products",
  "Ecommerce",
] as const;

export const expertiseLevels = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Expert",
] as const;

export const programmingLanguages = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Ruby",
  "PHP",
  "Java",
  "C#",
  "C++",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Objective-C",
  "Scala",
  "Haskell",
  "Erlang",
  "Zig",
  "Elixir",
  "Erlang",
  "Lua",
  "R",
  "ABAP",
  "SQL",
] as const;

export const languages = [
  "English",
  "Russian",
  "Belarusian",
  "Polish",
  "Lithuanian",
  "German",
  "Spanish",
  "French",
  "Italian",
  "Portuguese",
  "Dutch",
  "Turkish",
] as const;
